### PR TITLE
Create video archive page

### PR DESCRIPTION
**Pull request by tina-la**
Refs: https://github.com/elastic/website-development/issues/12660

### CODE REVIEW

**Comment by tina-la** [comment]
Hi team, please see time considerations below. Thanks 🙂 

- July 1: PR needs to be merged.
- July 2: Launch to production.
- July 3: Launch page

**Review by acsnyder — CHANGES_REQUESTED** [review]
Code changes look good.  The design looks a little different than the figma.  Is the gray section above the footer supposed to have gray rounded corners or just flow into the footer with a full gray background?

Another thing not related to the code review, these rounded corners look weird on screens larger than the container.  The rounded corners just stopping at the edges of the container and leaving white space to the left and right looks like an unfinished project.  Not the fault of this PR though, more of a design decision/oversight.

**Comment by acsnyder** [comment]
An image would probably help:  Here's the preview: https://elasticon-git-tl-12660-eon-video-archive-elastic-web-team.vercel.app/events/elasticon/archive

Screenshot 2024-07-01 at 2 31 17 PM

Here's the figma:
Screenshot 2024-07-01 at 2 32 21 PM

**Comment by tina-la** [comment]
@acsnyder - For now, I used the rounded gray background to have it match with https://www.elastic.co/events/elasticon.

If you look at https://www.elastic.co/events/elasticon, none of backgrounds have square corners.

For launching, we'll go with rounded. After launch, I'll iterate more after Design/UX makes more changes and sends me other assets. Thanks!

**Review by acsnyder — APPROVED** [review]
Gotcha.  LGTM!

**Pull request merged**
